### ISSUE TITLE
Chinese Keyboard

### ISSUE THREAD

**Issue by microspino** [picnoir/ultimate-writer#1]
Hope this is the right place to ask, if not sorry, feel free to close and delete this question :)

Really enjoyed you article (got it from Lobste.rs) about the building. I Would like to have more info about the chinees keyboard. Would you mind to give me a link or a model name/no.?

**Comment by picnoir** [comment]
You can use the `61 mechanical keyboard` keywords on ebay or ali-express. You'll find lot of these,.
