### ISSUE TITLE
Request: Support for PaPiRus PiHat

### ISSUE THREAD

**Issue by edglazer** [picnoir/ultimate-writer#3]
Hello!
Awesome project! I'm wondering how difficult it would be to add support for the PaPiRus PiHat range of screens? The largest they offer is 2.7", so it might not be very practical, but it's another option that some people might try?

Thanks!

**Comment by za3k** [comment]
It would probably be easy, but you'd need to do it, because it's not possible to add support without the hardware in front of you.

**Comment by edglazer** [comment]
Understandable, thanks!
